### ISSUE TITLE
Autorouter madness

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/Sayma_AMC#104]
![Zrzut ekranu z 2019-04-15 13 50 11](https://user-images.githubusercontent.com/24512604/56130558-877e4800-5f85-11e9-8257-86bf83bc12e2.png)

**Comment by marmeladapk** [comment]
![Zrzut ekranu z 2019-04-15 13 57 13](https://user-images.githubusercontent.com/24512604/56130918-71bd5280-5f86-11e9-919c-8476850820ed.png)

**Comment by marmeladapk** [comment]
![Zrzut ekranu z 2019-04-15 14 04 18](https://user-images.githubusercontent.com/24512604/56131321-64549800-5f87-11e9-8641-4b34bf11f1eb.png)
Shared via

**Comment by marmeladapk** [comment]
![Zrzut ekranu z 2019-04-15 14 05 32](https://user-images.githubusercontent.com/24512604/56131382-8b12ce80-5f87-11e9-91cf-3f59cac59f43.png)

**Comment by marmeladapk** [comment]
IC32A

![Zrzut ekranu z 2019-04-15 14 10 45](https://user-images.githubusercontent.com/24512604/56131632-48052b00-5f88-11e9-89e5-ccb9f80fb13c.png)

**Comment by marmeladapk** [comment]
Near IC21

![Zrzut ekranu z 2019-04-15 14 15 54](https://user-images.githubusercontent.com/24512604/56131903-00cb6a00-5f89-11e9-97a5-f80ab179f35c.png)

**Comment by marmeladapk** [comment]
Near C441
![Zrzut ekranu z 2019-04-15 14 24 03](https://user-images.githubusercontent.com/24512604/56132402-286f0200-5f8a-11e9-854f-99779337c5df.png)

**Comment by marmeladapk** [comment]
General remark: more vias to ground for caps on the right of the FPGA?

**Comment by marmeladapk** [comment]
Q1

![Zrzut ekranu z 2019-04-15 14 32 47](https://user-images.githubusercontent.com/24512604/56132862-5d2f8900-5f8b-11e9-9505-ed09c1521e78.png)

**Comment by marmeladapk** [comment]
Si5324 could use moure grounding vias

**Comment by marmeladapk** [comment]
C102
![Zrzut ekranu z 2019-04-15 14 36 21](https://user-images.githubusercontent.com/24512604/56133067-da5afe00-5f8b-11e9-9975-adec8643b8c3.png)

**Comment by marmeladapk** [comment]
3 capacitors share the same ground via near C355

**Comment by marmeladapk** [comment]
![Zrzut ekranu z 2019-04-15 16 23 14](https://user-images.githubusercontent.com/24512604/56140242-ccf94000-5f9a-11e9-97df-e0035208ad8a.png)

Not needed wobbles

**Comment by gkasprow** [comment]
some loops are intentional. The first one is to protect traces agaisnt ESD discharge.
