### ISSUE TITLE
Current shortage on 3V3P

### ISSUE THREAD

**Issue by kaolpr** [sinara-hw/Sayma_AMC#107]
In worst case scenario, when DDR termination draws maximum current and FMC draws maximum current allowed by FMC specification, MLVDS are used as well as both SFP we may have a severe overcurrent on 3V3 rail. 

Budget assumes 4A and in such situation about 5.8A can be drawn (**worst** case). After quick chat with @gkasprow the following solution is proposed:
* state that card is not fully FMC-compliant and 3V3 current shall not exceed 2A,
* move SFP to P5V0 rail (adding buck converter).

Above steps will make worst case load slightly less than 4A.

**Comment by gkasprow** [comment]
Let's add individual 3A buck for FMC 3V3.
NCP3710A which we already use would be fine.
