### ISSUE TITLE
Signals going over reference plane split

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/Sayma_AMC#112]
(LVDS signals were not listed)

L5:
- CDR_CLK_CLEAN1
- CDR_CLK_CLEAN2
- CDR_CLK_CLEAN3
- FCLKC (not sure if always LVDS)
- DDR3_64 signals (cross over 3V3 and MGTAVCC)
- P1V5 on P6 could be extended like this to cover all DDR32 signals, as no VCCINT vias are in this area
![Zrzut ekranu z 2019-04-19 09 21 20](https://user-images.githubusercontent.com/24512604/56412527-cdd4ef00-6284-11e9-9c2e-38c4834a40b9.png)

**Comment by gkasprow** [comment]
Yes, but this is a compromise. With such an extension, the VCCINT supply plane would be seriously affected causing DC drop. I moved it a little to cover most of the traces, but PI analysis will show us if it is possible.
