### ISSUE TITLE
Sayma AMC SI verification

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Sayma_AMC#115]
Results of DDR verification
![obraz](https://user-images.githubusercontent.com/4325054/57113408-b564da00-6d44-11e9-8231-b2dd4d466dd2.png)
![obraz](https://user-images.githubusercontent.com/4325054/57113417-c4e42300-6d44-11e9-80d4-4e500ad4f5d8.png)
![obraz](https://user-images.githubusercontent.com/4325054/57113427-d0374e80-6d44-11e9-9da0-8f69d5471e9c.png)
![obraz](https://user-images.githubusercontent.com/4325054/57113434-d88f8980-6d44-11e9-9d8b-6cbdc400e0fd.png)

**Comment by gkasprow** [comment]
![obraz](https://user-images.githubusercontent.com/4325054/57113463-f957df00-6d44-11e9-83ef-8d7edc9da1ef.png)
![obraz](https://user-images.githubusercontent.com/4325054/57113473-0aa0eb80-6d45-11e9-82c0-1ae0894da40d.png)
![obraz](https://user-images.githubusercontent.com/4325054/57113492-18567100-6d45-11e9-8cf6-3e8f0a13e4e2.png)
![obraz](https://user-images.githubusercontent.com/4325054/57113500-23110600-6d45-11e9-8276-140b90d40d45.png)

**Comment by gkasprow** [comment]
![obraz](https://user-images.githubusercontent.com/4325054/57113528-4471f200-6d45-11e9-85d4-7e6e69fe09e3.png)
![obraz](https://user-images.githubusercontent.com/4325054/57113551-59e71c00-6d45-11e9-891a-ec4e34263496.png)
![obraz](https://user-images.githubusercontent.com/4325054/57113560-64091a80-6d45-11e9-88c7-c219b30c9e46.png)
![obraz](https://user-images.githubusercontent.com/4325054/57113574-71bea000-6d45-11e9-8de5-789e5164a48b.png)
![obraz](https://user-images.githubusercontent.com/4325054/57113580-7be09e80-6d45-11e9-9947-950dd84882e2.png)

**Comment by gkasprow** [comment]
![obraz](https://user-images.githubusercontent.com/4325054/57113623-b4807800-6d45-11e9-8dac-9bb707eb1e41.png)
![obraz](https://user-images.githubusercontent.com/4325054/57113641-c2ce9400-6d45-11e9-9262-47f7a806e549.png)

**Comment by gkasprow** [comment]
The whole simulation including crosstalks and FR4 losses takes roughly 12hours on quad Xeon machine. Now I'm simulating DDR32 memory.

**Comment by gkasprow** [comment]
@sbourdeauducq I'm doing simulations for 800MT/s (400MHz clock) Is that sufficient?

**Comment by gkasprow** [comment]
DDR32 results
![obraz](https://user-images.githubusercontent.com/4325054/57165378-32508c00-6df7-11e9-83ca-47dfac613e8a.png)
![obraz](https://user-images.githubusercontent.com/4325054/57165390-3ed4e480-6df7-11e9-97a3-bf1cb2ec404f.png)
![obraz](https://user-images.githubusercontent.com/4325054/57165402-498f7980-6df7-11e9-87f2-86dcf2d6e1e6.png)
![obraz](https://user-images.githubusercontent.com/4325054/57165415-53b17800-6df7-11e9-98d3-2778bc047924.png)
![obraz](https://user-images.githubusercontent.com/4325054/57165429-5ca24980-6df7-11e9-9f5a-f84e17190a8e.png)
![obraz](https://user-images.githubusercontent.com/4325054/57165449-6926a200-6df7-11e9-9ffa-5c370028c36b.png)
![obraz](https://user-images.githubusercontent.com/4325054/57165464-70e64680-6df7-11e9-9286-25426e0a4213.png)
![obraz](https://user-images.githubusercontent.com/4325054/57165470-780d5480-6df7-11e9-8178-bf0265f9048a.png)

**Comment by sbourdeauducq** [comment]
>  I'm doing simulations for 800MT/s (400MHz clock) Is that sufficient?

The current ARTIQ/MiSoC does 1000MT/s (and we might want to crank that up in the future).

**Comment by gkasprow** [comment]
OK, so I will optimize it for 1066MT/s
