### ISSUE TITLE
DRC (PCB)

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/Sayma_AMC#119]
Fix remaining errors (I have around 260) from DRC. Also make sure to repour polygons before pushing new files to repository.

**Comment by marmeladapk** [comment]
@tprzywoz noticed that clearance rules are in the wrong order and supersede theoretically more specific rules (e.g. diff2diff).

**Comment by gkasprow** [comment]
That's OK with priorities. diff2others is disabled. I used it only for routing.
