### ISSUE TITLE
3V3_MP overcurrent during RTM startup

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/Sayma_AMC#130]
(Most probably it's overcurrent, we saw large dips in voltage when RTM started).
Changing R92 to 100k helped in Native-R5, but we'll need to test it on the rest of the boards.

@sbourdeauducq your AMC doesn't have this fix.

**Comment by sbourdeauducq** [comment]
Where is R92?

**Comment by marmeladapk** [comment]
![Zrzut ekranu z 2019-09-25 13 10 41](https://user-images.githubusercontent.com/24512604/65595941-25932700-df96-11e9-97d0-9654c7278c31.png)

**Comment by marmeladapk** [comment]
@sbourdeauducq Due to confusion if we can send this board I had a moment to implement this change on your Sayma.
