### ISSUE TITLE
FP connections

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Sayma_AMC#14]
Since we're now using MCX elsewhere, can we switch the MMCX connectors on Sayma AMC for MCX please (assuming there is room)? Thanks and apologies for the last minute switch!

**Comment by jbqubit** [comment]
@gkasprow @marmeladapk Can this change be accommodated? Seems like it's a trivial change but it does modify the BOM.

**Comment by hartytp** [comment]
To clarify, on v1.0 there were 2 SMA connectors on the FP. That didn't really work since they clashed with the USB connection and uTCA handle. This made them a PITA to use.

In the initial v1.2 schematic they were replaced with MMCX to solve these mechanical issues. Proposal here is to replace with MCX...

**Comment by gkasprow** [comment]
We have more place with FMC panels so it should be easier.

**Comment by gkasprow** [comment]
ups, U are talking about AMC..true, we can replace with MCX ones

**Comment by hartytp** [comment]
Yes, I mean on the AMC. Those SMAs always made me swear every time I used them.

I think it's also worth replacing the MMCXs on BaseMod with MCXs where possible to improve the mechanical reliability and compatibility with other boards, but that's a separate issue.

**Comment by gkasprow** [comment]
MCX won't fit on BaseMod,
I replaced SMAs with MCXs on the AMC.
