### ISSUE TITLE
BaseMod RF, output amplitude inconsistent

### ISSUE THREAD

**Issue by jbqubit** [sinara-hw/Sayma_AMC#142]
Issue raised on call with Creotech on 12/18. "RF output has correct frequency but every second channel has 2x amplitude." @marmeladapk says this might be due to error in BaseMod configuration. 

@sbourdeauducq Has M-Labs written a driver for BaseMod yet? I gather Cretoech would appreciate using your driver as a reference design.

**Comment by gkasprow** [comment]
Unitinialised attenuators often setup in a random way, I noticed it on Urukul.

**Comment by marmeladapk** [comment]
@jbqubit It not an error per se in configuration, it's just lack of configuration ;)

**Comment by marmeladapk** [comment]
@atcher0 fixed it yesterday before we had a chance to tell him that it's not needed.

**Comment by sbourdeauducq** [comment]
FWIW, the HMC542 datasheet says that reset held low "clears the shift register".
I do not know if reset affects the latch (I suppose we have to measure that ourselves, as is often the case when using anything from HMC) and thus if a pull-down resistor on reset would help with this minor wrinkle.

**Comment by sbourdeauducq** [comment]
The schematic says it does not affect the latch:
![image](https://user-images.githubusercontent.com/720864/71246579-ec2e4580-2351-11ea-9cad-804d1f433684.png)

So it would be pull-down on reset and pull-up on LE.

**Comment by gkasprow** [comment]
Yes, but first, someone must toggle the reset line :)

**Comment by sbourdeauducq** [comment]
According to the datasheet, reset is level-sensitive. But we would have that problem with the latch signal, yes (which is rising edge sensitive).
![image](https://user-images.githubusercontent.com/720864/71261588-b2246a00-2378-11ea-9756-6d7fe3cd079b.png)

**Comment by sbourdeauducq** [comment]
So if we really care about this, we need some complicated power-up sequencing of LE and reset pullup/pulldowns. HMC design strikes again...
But since there are also RF switches on our PCB, it doesn't really matter.

**Comment by sbourdeauducq** [comment]
And it's not a "latch" but a D flip-flop...

**Comment by sbourdeauducq** [comment]
> @sbourdeauducq Has M-Labs written a driver for BaseMod yet? I gather Cretoech would appreciate using your driver as a reference design.

Yes and it seems to work - at least I can read back the values.
See the latest commits in the ARTIQ repos.
