### ISSUE TITLE
Red LED on MCH in some crate slots

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/Sayma_AMC#147]
Some Saymas aren't communicating properly with MCH when inserted in some slots.

(we'll provide more details next week)

**Comment by jbqubit** [comment]
@marmeladapk What are details?

**Comment by marmeladapk** [comment]
It seems that some cards had troubles in 1st, 3rd and 5th slot, however when we didn't get any meaningful conclusion when we tried to pinpoint this issue. It seems to be solved now by changing something unrelated to communication with MCH. I know that this isn't a satisfactory answer, however previously troublesome cards are now working fine in multiple configurations in crate.

ed: We also changed build type from release to debug.
