### ISSUE TITLE
PUDC_B connection

### ISSUE THREAD

**Issue by atcher0** [sinara-hw/Sayma_AMC#15]
Now, PUDC_B is controlled with SW1/MMC -> R231, R230 should be removed

Note: according to [UG570](https://www.xilinx.com/support/documentation/user_guides/ug570-ultrascale-configuration.pdf) (page: 28/29) PUDC_B/M[2:0] pull-up resistors should be <=1kOhm (now - 10kOhm)

**Comment by gkasprow** [comment]
done
