### ISSUE TITLE
AMC photos

### ISSUE THREAD

**Issue by jbqubit** [sinara-hw/Sayma_AMC#150]
Please post photos of the stuffed Sayma_AMC for contract accounting. 

https://github.com/sinara-hw/Sayma_AMC/wiki/Sayma_v2_contract_creotech#c332-ht3-manufacturing-baseline-testing

Sayma AMC v2.0: print 10 PCBs, stuff 6

**Comment by akaminska** [comment]
1907180PW0009A0103
![IMG_20191213_170109](https://user-images.githubusercontent.com/45766037/78681790-77c1e700-78ed-11ea-90b4-4e8619aa70be.jpg)
![IMG_20191213_170127](https://user-images.githubusercontent.com/45766037/78681810-7db7c800-78ed-11ea-9b47-3e7a7f5a4f46.jpg)

**Comment by akaminska** [comment]
1907180PW0009A0104
![IMG_20191213_170748](https://user-images.githubusercontent.com/45766037/78682097-dd15d800-78ed-11ea-995e-32e9e61b4f3c.jpg)
![IMG_20191213_170803](https://user-images.githubusercontent.com/45766037/78682105-df783200-78ed-11ea-9330-3004efa2b73e.jpg)

**Comment by akaminska** [comment]
1907180PW0009A0106
![IMG_20191213_171100](https://user-images.githubusercontent.com/45766037/78682278-11899400-78ee-11ea-9b8e-e3ffec922794.jpg)
![IMG_20191213_171112](https://user-images.githubusercontent.com/45766037/78682291-14848480-78ee-11ea-9d3b-f040ccad1edf.jpg)

**Comment by akaminska** [comment]
1907180PW0009A0105
![IMG_20191213_173830](https://user-images.githubusercontent.com/45766037/78682805-c0c66b00-78ee-11ea-9be1-af260b469d06.jpg)
![IMG_20191213_173840](https://user-images.githubusercontent.com/45766037/78682813-c3c15b80-78ee-11ea-86cc-b965f20e1745.jpg)

**Comment by akaminska** [comment]
1907180PW0009A0107
![IMG_20191216_170032](https://user-images.githubusercontent.com/45766037/78682939-ee131900-78ee-11ea-985d-1b16a3b2c24a.jpg)
![IMG_20191216_170047](https://user-images.githubusercontent.com/45766037/78682952-f10e0980-78ee-11ea-828f-84bb5842a2e5.jpg)

**Comment by akaminska** [comment]
1907180PW0009A0108
![IMG_20191216_171157](https://user-images.githubusercontent.com/45766037/78683098-274b8900-78ef-11ea-8fdf-84d4f36d67f2.jpg)
![IMG_20191216_171210](https://user-images.githubusercontent.com/45766037/78683104-29ade300-78ef-11ea-9a58-c07fe553f28f.jpg)

**Comment by akaminska** [comment]
Unpopulated PCBs
![IMG_2548](https://user-images.githubusercontent.com/45766037/78684199-7d6cfc00-78f0-11ea-8323-edc2539feb75.jpg)
![IMG_2552](https://user-images.githubusercontent.com/45766037/78684283-92e22600-78f0-11ea-8552-d542b4d31d22.jpg)

**Comment by jbqubit** [comment]
Thank you. Please also post photo of at least one AMC with front panel installed. Ideally front view.

**Comment by akaminska** [comment]
Please remember that these panels are "prototypes" as well, we definitely aim for better quality for the final product...
![SAYMA AMC 1907180PW0009A0103 PANEL](https://user-images.githubusercontent.com/45766037/79003063-13539180-7b52-11ea-99ed-8928c5ffe1b8.JPG)
![SAYMA AMC 1907180PW0009A0111 GÓRA](https://user-images.githubusercontent.com/45766037/79003110-2bc3ac00-7b52-11ea-913e-67b8405922e8.JPG)

**Comment by jbqubit** [comment]
Thank you.
