### ISSUE TITLE
connect I2C switch reset to FPGA

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Sayma_AMC#17]
Having to reload the FPGA is annoying. With a bit of software support, this can recover from I2C hangs due to breakage on SFPs, FMCs, RTMs.
IC53
![image](https://user-images.githubusercontent.com/1338946/50291414-d2bc9a00-046e-11e9-948c-ec9f4fa3fefd.png)

We might also want to connect the I2C bus to the FTDI chip like on Kasli. Maybe one VUART bus could go.

**Comment by gkasprow** [comment]
added I2C_SW_FPGA_RESETn to ball M15 of FPGA.
Isn't one VUART used to talk with RTM FPGA?
