### ISSUE TITLE
rename REFCLK224_C_N -> 228

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Sayma_AMC#18]
wrong name
![image](https://user-images.githubusercontent.com/1338946/50291712-9ccbe580-046f-11e9-9153-9f5f9532d651.png)

and REFCLK227_C_N -> 225

**Comment by gkasprow** [comment]
done
![obraz](https://user-images.githubusercontent.com/4325054/53343498-cb9f8580-3910-11e9-8f45-b96faa46ff70.png)
