### ISSUE TITLE
MMC HW ID is not changed

### ISSUE THREAD

**Issue by atcher0** [sinara-hw/Sayma_AMC#22]
MMC HW ID is not changed and does not match FPGA HW ID.

**Comment by gkasprow** [comment]
done
![obraz](https://user-images.githubusercontent.com/4325054/53345863-27204200-3916-11e9-9a92-5bb5a9a0ab21.png)

![obraz](https://user-images.githubusercontent.com/4325054/53345876-2daeb980-3916-11e9-8915-8252038a0a03.png)
