### ISSUE TITLE
ETH PHY configuration

### ISSUE THREAD

**Issue by atcher0** [sinara-hw/Sayma_AMC#23]
ETH PHY CONFIG pin should be connected to VSS or VDDO to select VDDO_LEVEL = 3.3V/1.8V (current configuration selects VDDO_LEVEL = 2.5/1.8)

**Comment by gkasprow** [comment]
done
![obraz](https://user-images.githubusercontent.com/4325054/53345241-b4629700-3914-11e9-8ce7-bca011c88e89.png)
