### ISSUE TITLE
make sure all transceiver channels can be clocked from uFL

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Sayma_AMC#24]
So we can bypass any clocking circuit breakage.

**Comment by gkasprow** [comment]
224 cannot but we clock it from CDR and 200MHz oscillator. 
225 can be clocked
226 - cannot but we have it connected to RTM and HMC7043. If necessary I can add ufl
227 cannot but we have it connected to RTM and HMC7043 and also DNP oscillator
228 can be clocked

**Comment by sbourdeauducq** [comment]
226 should be sufficient no? And there is a spare CLK pin there. https://github.com/sinara-hw/Sayma_AMC/issues/47

**Comment by gkasprow** [comment]
OK, moved ufl to 226
