### ISSUE TITLE
check net names are exactly the same on both sides of the AMC<->RTM connector

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Sayma_AMC#25]

**Comment by hartytp** [comment]
Related:
- [ ] Didn't we agree to rename `RTM_FPGA_GTP_{}` to just `RTM_FPGA_GTP` (i.e. same naming as other GTP signals)? If there is no difference between these signals and the other GTP lines on the AMC FPGA then why name them differently. IME it's generally better not to encode the functionality for these kinds of signals in the name (e.g. I can imagine using Sayma AMC with other RTMs which might not connect these lines to an RTM FPGA.)

**Comment by gkasprow** [comment]
done
