### ISSUE TITLE
Replace GT_CLK{1,2}_IN with more LVDS?

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Sayma_AMC#26]
Do we need these AMC<->RTM clock lines now that there is nothing on the RTM to drive them with?

If we do need to keep them, at the very least, let's zero index the names!

**Comment by gkasprow** [comment]
we need one to clock the gigabit transceiver. @sbourdeauducq which one shall I leave? or leave both of them? We need one more LVDS for SYSREF.

**Comment by gkasprow** [comment]
I will leave one clock routed to bank 226. We don't need one routed to bank 227.
From bank 226 we can supply the clock to bank 227 and 228 and also 225 and 224.
Am I right?

**Comment by gkasprow** [comment]
done
