### ISSUE TITLE
DDR64 clocking with MIG

### ISSUE THREAD

**Issue by kaolpr** [sinara-hw/Sayma_AMC#30]
There is an issue when Xilinx MIG is to be used instead of MiSoC DDR core for DDR64. When one wants to use MIG there is no other way but to provide clock signal using UFL connector. 

It is so because according to the "Clocking" sections of (PG150) _LogiCORE IP UltraScale Architecture-Based FPGAs Memory Interface Solutions_ clock source must be placed in the same IO column as memory interface and no external MMCM can be used (as cascading MMCMs is not allowed and another MMCM is instantiated in MIG).

The problem could be solved by adding 200 MHz oscillator and connecting it to one of the banks in the memory interface column (44 - 48). It may require moving UFL connector elsewhere as I don't see any free differential clock-capable inputs in those banks.

**Comment by gkasprow** [comment]
We can also route unused reference buffer outputs to DDR clock inputs.

**Comment by kaolpr** [comment]
We can safely assume that this signal will be 125 MHz in all cases?

**Comment by gkasprow** [comment]
All oscillators are programmable so we can assume it, however in ARTIQ we use either 100 or 150MHz

**Comment by gkasprow** [comment]
added 2 clock paths
![obraz](https://user-images.githubusercontent.com/4325054/53342689-da853880-390e-11e9-8016-40885e92e0eb.png)
![obraz](https://user-images.githubusercontent.com/4325054/53342705-e53fcd80-390e-11e9-87fd-d7883aec408a.png)

![obraz](https://user-images.githubusercontent.com/4325054/53342770-0a344080-390f-11e9-9165-bf148539fa89.png)

**Comment by sbourdeauducq** [comment]
So this clock gets replaced with the CDR clock, correct?
```
    ("sysclk1_300", 0,
        Subsignal("p", Pins("F18")),
        Subsignal("n", Pins("F17")),
        IOStandard("DIFF_SSTL15_DCI"), Misc("OUTPUT_IMPEDANCE=RDRV_40_40")
    ),
```

**Comment by gkasprow** [comment]
Yes.
