### ISSUE TITLE
FPGA pinout/netlist

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Sayma_AMC#31]
@gkasprow for the stub ARTIQ port we need the FPGA pinout

**Comment by gkasprow** [comment]
I manually replaced slashes with semicolons :)

**Comment by gkasprow** [comment]
Here you go.
Altium makes it much more elegant
[FPGA_pins.xlsx](https://github.com/sinara-hw/Sayma_AMC/files/2900901/FPGA_pins.xlsx)

**Comment by gkasprow** [comment]
update

**Comment by gkasprow** [comment]
I forgotten to zero-index signals SMA_IOx
