### ISSUE TITLE
IC58 TPS74401 Vin under recommended voltage range

### ISSUE THREAD

**Issue by tprzywoz** [sinara-hw/Sayma_AMC#32]
IC58 LDO input voltage is 1.0 V.
In Electrical Characteristics minimum Vin is Vout (0,95 V) + Vdo (which is extreamly low thanks to 31 mA load current). But minimum Input supply voltage in Recommended Operating Conditions is 1.1 V.

**Comment by gkasprow** [comment]
since VCCINT is 0.95V we don't need it anymore
