### ISSUE TITLE
Ethernet PHY programming

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Sayma_AMC#39]
I wonder if it is really necessary to allow connecting the PHY MDIO (as well as MODE and RESET) to the MMC. The FPGA should be able to program it and handle MODE/RESET, and the MMC does not need Ethernet.

**Comment by gkasprow** [comment]
true, the PHY needs switching from 1000base-T to 1000base-x mode by setting one bit. By default it talks to the RJ45 connector. For diagnostic purposes, I added pin header for such a connector.
If you can handle this, I can scrap the mux.

**Comment by sbourdeauducq** [comment]
Yes, scrap the mux. What register(s) should be written exactly?

**Comment by sbourdeauducq** [comment]
In https://github.com/jbqubit/saymapp/blob/master/pp.md#ethernet
"Configuration of M88E1512 is by static pin strapping: 1 Gbps, GMII, 1000BASE-X."
Is that incorrect?

**Comment by gkasprow** [comment]
not really. Look [here](https://www.marvell.com/documents/eoxwrbluvwybgxvagkkf/) p39
One needs to set one bit in register
![obraz](https://user-images.githubusercontent.com/4325054/53502087-a7c57680-3aad-11e9-84d6-e545b183ac76.png)
That's why I wanted to do it via MMC so you don't have to talk to the PHY.

**Comment by sbourdeauducq** [comment]
Doing it in the FPGA is certainly easier and less frustrating.

**Comment by gkasprow** [comment]
OK, so let's scrap the mux and close it.

**Comment by gkasprow** [comment]
do you need the PHY reset to be routed to the FPGA?

**Comment by gkasprow** [comment]
and what about the INT?

**Comment by sbourdeauducq** [comment]
I need the PHY reset (always useful to recover from problems), INT is not necessary but can be routed if easy.

**Comment by gkasprow** [comment]
OK, managed to connect both.
