### ISSUE TITLE
signal names on AMC for programming RTM FPGA

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Sayma_AMC#40]
The signal names in the .txt files do not look good, e.g. for CCLK:
```
\$6N9201\  \R308\-\1\ \IC37\-\J25\
```
Is this just because of the series resistors/jumpers e.g. R308?
What is the purpose of those resistors? What about using test points instead?

**Comment by gkasprow** [comment]
These resistors are assembly options. It is still possible to chain both FPGAs and load from the same FLASH...
I added nets with _R
![obraz](https://user-images.githubusercontent.com/4325054/53354525-3956ac00-3927-11e9-99b5-5154b1abe0fb.png)
