### ISSUE TITLE
REC_CLOCK_P/N "NOT USED"?

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Sayma_AMC#41]
Why is this signal marked as "NOT USED" on the schematics? It is a crucial signal for DRTIO with the Si5324.

**Comment by sbourdeauducq** [comment]
![image](https://user-images.githubusercontent.com/720864/53322526-9a29b880-3916-11e9-95ce-294c78805700.png)

**Comment by gkasprow** [comment]
true.
Please use Altium schematics for any new issues. I did a lot of cleaning while porting to Altium.
I added it to release
https://github.com/sinara-hw/Sayma_AMC/releases/tag/v2.0rc2
