### ISSUE TITLE
ALT_PORT0 must be usable at the same time as RTM_FPGA_GTP

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Sayma_AMC#42]
* RTM_FPGA_GTP is required for DRTIO with the RTM. We actually plan to use DRTIO *exclusively* in the future for communicating with the RTM.
* ALT_PORT0 is the preferred way of using Ethernet; if the GTH behaves itself we don't need an external PHY chip.

Since we are out of transceiver channels, I propose removing one of the two SFPs and allocating it to either ALT_PORT0 or RTM_FPGA_GTP.

Also, the possible connection to FAT_PIPE1 of RTM_FPGA_GTP does not seem necessary, since 
RTM_FPGA_GTP will be a requirement for using the RTM. It makes more sense to make a possible connection to the remaining SFP instead.

**Comment by sbourdeauducq** [comment]
If there is an interest in keeping two SFPs, sharing a SFP with ALT_PORT0 is also an option.

**Comment by gkasprow** [comment]
done
![obraz](https://user-images.githubusercontent.com/4325054/53342094-7f9f1180-390d-11e9-9cc9-0eff4198a407.png)
