### ISSUE TITLE
Sayma AMC v2 design changes

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Sayma_AMC#44]
Sayma AMC v2 apart from fixing issues reported in #600 undergoes major modifications:
- Ethernet PHY
- Clock distribution with [WR support](https://github.com/sinara-hw/meta/issues/15)
- FTDI JTAG -copied from Kasli
- JTAG switch - copied from Xilinx devkit, but with AMC access

**Comment by gkasprow** [comment]
added clock path between CDR and SDRAM banks to enable Xilinx IP using during production tests
#30

**Comment by gkasprow** [comment]
added Silabs CDR test points

**Comment by gkasprow** [comment]
added TVS #13

**Comment by gkasprow** [comment]
the output of Si5324 buffer routed to the bank 226

**Comment by sbourdeauducq** [comment]
> the output of Si5324 buffer routed to the bank 226

Which output of Si5324?
Why?

**Comment by gkasprow** [comment]
to make sure every GTX can drive DRTIO

**Comment by sbourdeauducq** [comment]
I assume you mean the output of the CDR clock mux/distributor IC44.

OK. Not strictly necessary (the JESD transceivers do not need det-lat with the RTIO clock and also can be clocked from the RTM), but fine to have if it's easy and doesn't break anything.

**Comment by gkasprow** [comment]
I think we can close it. It's hard to track all changes since the design is so different from v1.
