### ISSUE TITLE
MGTREFCLK uFL naming inconsistencies

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Sayma_AMC#48]
228/224:
![image](https://user-images.githubusercontent.com/720864/53382051-dcea9f80-39ad-11e9-822f-43ab18aa3192.png)

225/227:
![image](https://user-images.githubusercontent.com/720864/53382061-e2e08080-39ad-11e9-8669-a715d6f56f63.png)

**Comment by gkasprow** [comment]
fixed already
