### ISSUE TITLE
DNP FPGA daisy chain configuration loading resistors R200-R227

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Sayma_AMC#49]
DNP by default. We currently don't use daisy chain loading but slave serial via AMC FPGA bank 65.

![image](https://user-images.githubusercontent.com/1338946/53477786-bdb74500-3a75-11e9-8100-cfb03608f107.png)

These were R176-R180 on Sayma AMC v1.0

**Comment by gkasprow** [comment]
true, fixed
