### ISSUE TITLE
DNP ALT_PORT0 jumpers

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Sayma_AMC#50]
Depending on how you do the routing, you'll probably want to DNP C182-C185.

![image](https://user-images.githubusercontent.com/1338946/53561518-684f6680-3b4f-11e9-8796-c92b7697a29f.png)
![image](https://user-images.githubusercontent.com/1338946/53561554-77361900-3b4f-11e9-87ba-a8ba0c0b141e.png)

**Comment by gkasprow** [comment]
done

**Comment by sbourdeauducq** [comment]
GTH Ethernet is working on Sayma v1 now, and we'll probably want to use that (no need to configure the PHY chip and no issues with RGMII timing) - so it's the capacitors for the other path (with the PHY chip) that should be DNP'd.

**Comment by sbourdeauducq** [comment]
Do not remove the PHY chip though, just in case there are unforeseen transceiver problems.

**Comment by gkasprow** [comment]
@sbourdeauducq in such case we will loose one SFP. Maybe it should be not mounted?

**Comment by sbourdeauducq** [comment]
OK.
