### ISSUE TITLE
transmission line transformers compensation caps, capacitor jumpers, TCKC

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Sayma_AMC#53]
On the RTM:

![image](https://user-images.githubusercontent.com/1338946/53695959-46a9e580-3dc2-11e9-991b-6593977ccda6.png)

But on the AMC:

![image](https://user-images.githubusercontent.com/1338946/53695962-51fd1100-3dc2-11e9-99f4-96e9e804def0.png)

* Add the 0.5 pF compensation caps as well.
* Mark C272/C270 DNP

![image](https://user-images.githubusercontent.com/1338946/53696010-ea939100-3dc2-11e9-9782-ee8b5441013a.png)

* Also remove the TCKC_B_N/TCKC_B_P net labels. AFAICT they are wrong/confusing.

**Comment by gkasprow** [comment]
done
![obraz](https://user-images.githubusercontent.com/4325054/53808550-d67e9980-3f52-11e9-9e43-38e7cbdcfd7f.png)
