### ISSUE TITLE
FMC naming inconsistency

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Sayma_AMC#56]
"DP0_M2C" signals connecting to "DP1_C2M":
![image](https://user-images.githubusercontent.com/720864/54104067-8cd9f700-4409-11e9-8eef-af4770e61c45.png)

**Comment by gkasprow** [comment]
true, fixed.
![obraz](https://user-images.githubusercontent.com/4325054/54128525-92850c00-440c-11e9-9168-70ed7d2d96d7.png)
