### ISSUE TITLE
git tag

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Sayma_AMC#57]
The git tag for v2.0rc4 should be "v2.0rc4" and not "v20rc4".
The git documentation explains how to remove tags.

**Comment by gkasprow** [comment]
I changed it in releases. Is it sufficient?

**Comment by sbourdeauducq** [comment]
No: https://github.com/sinara-hw/Sayma_AMC/releases
You need to make note of the commit ID (e4bb4899cf2f2b5a73dc6fdeb7a25576b612e0c5), delete the tag from both GitHub and your local copy, create it again at the correct commit, and push it again.
If you have not done this before, I suggest making a full backup of the repository before doing it, in case you break something.
