### ISSUE TITLE
connect DDMTD input to quad 224

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Sayma_AMC#59]
Quad 224 is where DRTIO CDR is happening, and the output from this quad may be more precise than after it has gone through more FPGA routing to reach quad 225 where MGT_CDR_CLK is currently connected.
OBUFDS_GTE3 may be even unable to obtain clocks from adjacent quads (see Figure 2-3 in ug576: I don't see a path from other quads).

I suggest swapping MGT_CDR_CLK and FCLKAC_N - Ethernet clocking will be fine with one quad crossed, and I have no use for the AMC fabric clock.

**Comment by gkasprow** [comment]
done
![obraz](https://user-images.githubusercontent.com/4325054/54128197-d592af80-440b-11e9-8209-76d3b856767c.png)

![obraz](https://user-images.githubusercontent.com/4325054/54128227-e8a57f80-440b-11e9-9bee-54d5c1a72894.png)
