### ISSUE TITLE
SFPs get stuck in Sayma

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Sayma_AMC#61]
And pins of the cage get bent during removal. See the first 3 pins at the bottom of the cages on the picture:
![stuck_sfp](https://user-images.githubusercontent.com/720864/39686373-4000f9c0-51fb-11e8-9944-ce72c5d4ef10.jpg)

**Comment by gkasprow** [comment]
I added panel cutout to solve the issue
![obraz](https://user-images.githubusercontent.com/4325054/54915557-b3af2780-4ef7-11e9-8662-7dc6fce36e75.png)
