### ISSUE TITLE
consider making all UFLs MMCX

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Sayma_AMC#63]
It would be easier if I didn't have to stock two types of cable. If there are layout/mechanical reasons why this isn't easy for all connectors then it's fine to leave things how they are.

**Comment by sbourdeauducq** [comment]
uFLs are lower-profile and make jumper cables slightly easier to use e.g. if the board has to be put into the uTCA chassis with additional jumper cables installed (as is necessary now for DAC synch on v1).

**Comment by sbourdeauducq** [comment]
For example, it still fits in the uTCA crate with uFL jumper cables on the bottom side of the boards.

**Comment by gkasprow** [comment]
I placed all uFL connectors on the bottom of the board because of clock distribution circuits resites there
