### ISSUE TITLE
DNP WR LVPECL bias resistors

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Sayma_AMC#64]
R378 and R363 should be DNP by default since we use LVCMOS DCXOs

**Comment by hartytp** [comment]
Also shouldn't R375 be populated? (Is this supposed to be a capacitor to ground, or a 0R resistor?)

**Comment by hartytp** [comment]
In fact, generally, please can someone double check the LVCMOS to LVDS conversion at the helper DCXO output. Thanks!

**Comment by jbqubit** [comment]
@marmeladapk Can you do this?

**Comment by gkasprow** [comment]
@hartytp I think it is fine.
The CMOS oscillator generates too high voltage for LVDS input. That's why we need R377 and R378 assembled. R363 is also part of it.
