### ISSUE TITLE
Transceiver clocking

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Sayma_AMC#7]
- How do we want to clock the AMC transceivers?
- more generally, are you happy with the clock connections on the AMC<->RTM connector? Do you want any other clock lines between the two boards? If so, what should they connect to?

**Comment by gkasprow** [comment]
So far there are 2 clock input to the AMC MGTs + one general clock input for FPGA GC routed to the clock fanout on RTM.

**Comment by gkasprow** [comment]
we can route it to the Si5324 input. Does it support zero skew buffer mode ?

**Comment by gkasprow** [comment]
I added output of ADCLK948 to the free input of bank 226.
