### ISSUE TITLE
"Si5325" typo

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Sayma_AMC#70]
![image](https://user-images.githubusercontent.com/720864/54736816-e9969800-4be7-11e9-9748-08960cc8700b.png)

**Comment by sbourdeauducq** [comment]
Also, why is that a "WR clock input"? What are the exact use cases for this connector and signal?

**Comment by hartytp** [comment]
@sbourdeauducq It's not really a WR clock input at all. IIRC, it's just an unbuffered connector that goes to a GC pin.

The main use WR case I can think of for WR would be the reference clock if Sayma were used as the master. However, I suspect that it will be useful for testing and debugging the WR implementation. But, I would support a better name for the signal.

**Comment by sbourdeauducq** [comment]
Let's just call it "AMC external clock input".
