### ISSUE TITLE
option to clock JESD transceivers from HMC7043?

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Sayma_AMC#72]
We don't need it in theory for DRTIO scenarios, but would it be difficult to get one HMC7043 output to the JESD transceivers, e.g. instead of CLK_RFU_N? Generally, this also lets the RTM clock the transceivers.

**Comment by sbourdeauducq** [comment]
@gkasprow ping

**Comment by gkasprow** [comment]
We had such clock before - there were 2 GBT clocks routed and finally, we decided to leave only one in favor of additional LVDS pair.
I don't have enough pins in RTM. It's too late to do such serious modification when layout is done. However, if it is really needed one can use ufl cable and connect HMC with FPGA.
