### ISSUE TITLE
I2C address map

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/Sayma_AMC#76]
- Mux port 0: does each FMC have those two chips listed? They are not placed on Sayma
- remove note on the left in I@C_MUX schematics, it has information from older boards
- add a note on mux port 5, that XR77 is only present when module with it is inserted?
- in Thermomenters note that IC49 has 0x51 address for EEPROM and 0x59 for EUI access (read only)? Though it is noted on I2C_MUX table
- LM75 on mux port 7 has 0x4f instead of 0x4a address
- on RTM ports (table on the right): mux port 0 and 2 are analog mezzanine 0 and 1 (or 1 and 2, depending on how you count) and basemods currently have only EEPROM and ADT chips (address: 0x48)
- rtm mux port 1, 3 and 4 are empty- RTM still has XR chip, will it be removed as well?

**Comment by gkasprow** [comment]
Mux port 0 assumes FMC module plugged with the chips.
I assumed chip present also on TestMod boards where I2C extenders are installed
each mezzanine has 2x I2C buses.
