### ISSUE TITLE
Missing files when cloning project from repository

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/Sayma_AMC#77]
Altium shows errors when opening project.

- SFP.Harness
- Thermomenters.Harness
- RTM_CON.Harness
- USB_SERIAL_QUAD.Harness
- SI5324_CLK_RECOVERY.Harness
-SI5324_CDR_WR_oscillators.Harness
- SDRAM_DDR3_4x16.Harness
- SDRAM_DDR3_2x16.Harness

**Comment by gkasprow** [comment]
it should work now.
