### ISSUE TITLE
Invalid IC44/~CLK0 termination

### ISSUE THREAD

**Issue by kaolpr** [sinara-hw/Sayma_AMC#78]
In default variant IC44/CLK0 is single-ended. According to [datasheet](https://www.analog.com/media/en/technical-documentation/data-sheets/ADCLK948.pdf) single-ended AC coupled input should be connected like that:
![image](https://user-images.githubusercontent.com/9166701/55228143-b1134180-5219-11e9-8633-d769bdcae25a.png)
however unused ~CLK0 is only connected to ground via 100 nF capacitor.

**Comment by gkasprow** [comment]
they are equivalent from the signal point of view. 100nF capacitor makes a short circuit for RF frequencies.
