### ISSUE TITLE
Helper_CLK variant connections

### ISSUE THREAD

**Issue by kaolpr** [sinara-hw/Sayma_AMC#82]
![image](https://user-images.githubusercontent.com/9166701/55229834-5af4cd00-521e-11e9-8a9c-96f77de4ada3.png)

- What is a point of having R375? In what case it should be mounted?
- It looks like distance between current location of R386 and J33 may result in having a stub. Should R386 be mounted by default?

**Comment by gkasprow** [comment]
with R375 we increase the signal amplitude
