### ISSUE TITLE
Inconsistent GT naming

### ISSUE THREAD

**Issue by kaolpr** [sinara-hw/Sayma_AMC#84]
There is naming inconsistency in `FPGA_Banks_224_225_226_227_228` sheet: GT16 (MGTH3_224) is swapped in the sheet whereas all other GT lines are not. 

At least a note should be made to emphasize that fact as GT16 are the only lines in RTM_GT having direction different than given in the label.

**Comment by gkasprow** [comment]
OK, changed on both AMC and RTM to keep the naming consistent.
