### ISSUE TITLE
LTM4644 review

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/Sayma_AMC#90]
- change undefined resistors to 10pF DNPed capacitors and add a note about their purpose. Right now it looks like voltage divider.
- Why is SVIN connected to P5V0 instead of P12V0?

Symbol pins were checked against DS.

**Comment by gkasprow** [comment]
undefined resistors are to support LTM4644A chip in case of issues with availability. The only difference is the lack of internal feedback resistors. I added a note.
We use 5V VIN to improve efficiency.
