### ISSUE TITLE
Testpoints

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/Sayma_AMC#92]
- SDA testpoint has silkscreen in pad
![Zrzut ekranu z 2019-04-08 16 24 47](https://user-images.githubusercontent.com/24512604/55731652-d9215280-5a1a-11e9-9806-ac8799669c28.png)
- LTM4644 has unlabeled testpoints
- Many testpoints do not have names of signals, only e.g "TP4" is written
- TP15, TP14 are under front panel

**Comment by gkasprow** [comment]
can't move TP15,TP16 away without breaking SI. Other issues were fixed
