### ISSUE TITLE
IC2 (LPC "optional" memory) use case

### ISSUE THREAD

**Issue by kaolpr** [sinara-hw/Sayma_AMC#93]
Do we still need IC2 (MT25QL256ABA8ESF-0AAT)? It is currently mounted by default.

I guess it originates from the times when LPC had Ethernet connection to enable easy updates of gateware. However now, when LPC is not connected to port 0 anymore, remote update would have to be done using I2C what sounds like a bit of pain...

Additionally IC2 draws up to 35 mA of precious 3V3MP (limit for AMC+RTM is 180 mA).

**Comment by gkasprow** [comment]
we do not have a use case for it so can make it DNP
