### ISSUE TITLE
No fiducial targets

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/Sayma_AMC#94]
On both sides

**Comment by marmeladapk** [comment]
(or if these pads are fiducial targets then this pad is probably too close to chip)
![Zrzut ekranu z 2019-04-15 14 06 53](https://user-images.githubusercontent.com/24512604/56131537-fbb9eb00-5f87-11e9-8654-def49cf237b5.png)

**Comment by gkasprow** [comment]
they are Xpedition leftovers. I added right ones to the schematics.
