### ISSUE TITLE
3V3MP power budget

### ISSUE THREAD

**Issue by kaolpr** [sinara-hw/Sayma_AMC#99]
I've noticed some issues regarding 3V3MP power budget:

* missing IC2 (MT25QL256ABA8ESF) memory (35 mA),
* missing IC5 (SN74CB3T3257PW + load) JTAG buffer (5 mA),
* N25Q256A13ESF40 2x should be MT25QL256ABA8ESF and it is not MP (-20 mA),
* TCA9548 x2 will not draw 100 mA, I guess it was supposed to be 100 uA.

After having fixed above, sum of 3V3MP current is 316 mA, whereas mTCA specification states that AMC should draw no more than 150 mA alone and 180 mA with RTM connected.

To solve this issue we can:

* remove IC2 (#93),
* connect IC5 to P3V3.

Then budget for MMC is ~120 mA what should be taken into account when developing MMC firmware.

**Comment by gkasprow** [comment]
IC2 is DNP
IC5 must be connected to RTM power
ARM power consumption was placed with large margin. We won't consume 200mA for sure.
